package com.goldsignal.data.mock

import android.content.res.AssetManager
import com.goldsignal.data.AppJson
import com.goldsignal.data.DataSource
import com.goldsignal.data.GoldRepository
import com.goldsignal.model.BacktestRequest
import com.goldsignal.model.BacktestResponse
import com.goldsignal.model.CurrentResponse
import com.goldsignal.model.EventsResponse
import com.goldsignal.model.HealthResponse
import com.goldsignal.model.HistoryReport
import com.goldsignal.model.HistoryResponse
import com.goldsignal.model.IndicatorDetail
import com.goldsignal.model.SignalResponse
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Serves the fixtures in assets/mock. They are generated by the real Python engine
 * (backend/scripts/generate_android_fixtures.py) on illustrative data.
 */
class MockGoldRepository(private val assets: AssetManager) : GoldRepository {
    override val source = DataSource.MOCK

    private suspend fun text(name: String): String = withContext(Dispatchers.IO) {
        assets.open("mock/$name").bufferedReader(Charsets.UTF_8).use { it.readText() }
    }

    override suspend fun signal(): SignalResponse = AppJson.decodeFromString(text("signal.json"))
    override suspend fun current(): CurrentResponse = AppJson.decodeFromString(text("current.json"))
    override suspend fun indicator(code: String): IndicatorDetail =
        AppJson.decodeFromString(text("indicator_$code.json"))
    override suspend fun events(): EventsResponse = AppJson.decodeFromString(text("economic_events.json"))
    override suspend fun history(): HistoryResponse = AppJson.decodeFromString(text("history.json"))
    override suspend fun historyReport(): HistoryReport = AppJson.decodeFromString(text("history_report.json"))
    override suspend fun health(): HealthResponse = AppJson.decodeFromString(text("health.json"))

    /**
     * Demo only: one fixed synthetic run. Monetary values are scaled to the requested capital
     * (returns do not depend on capital); the date range cannot change until Phase 6.
     */
    override suspend fun backtest(request: BacktestRequest): BacktestResponse {
        val demo: BacktestResponse = AppJson.decodeFromString(text("backtest_demo.json"))
        val k = request.capital / demo.request.capital
        return demo.copy(
            request = demo.request.copy(capital = request.capital),
            strategy = demo.strategy.copy(finalValue = demo.strategy.finalValue * k),
            buyAndHold = demo.buyAndHold.copy(finalValue = demo.buyAndHold.finalValue * k),
            equityCurve = demo.equityCurve.map { it.copy(strategy = it.strategy * k, benchmark = it.benchmark * k) },
        )
    }
}
