package com.goldsignal

import com.goldsignal.data.AppJson
import com.goldsignal.model.BacktestResponse
import com.goldsignal.model.CentralBankExtra
import com.goldsignal.model.CurrentResponse
import com.goldsignal.model.DataStatus
import com.goldsignal.model.EconExtra
import com.goldsignal.model.EventsResponse
import com.goldsignal.model.FedExtra
import com.goldsignal.model.GramExtra
import com.goldsignal.model.IndicatorDetail
import com.goldsignal.model.NominalExtra
import com.goldsignal.model.Regime
import com.goldsignal.model.SignalLabel
import com.goldsignal.model.SignalResponse
import kotlinx.serialization.json.decodeFromJsonElement
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/** The bundled fixtures (generated by the Python engine) must decode into the app's contract types. */
class FixtureParsingTest {
    private val dir = listOf(File("src/main/assets/mock"), File("app/src/main/assets/mock")).first { it.isDirectory }
    private fun read(name: String) = File(dir, name).readText(Charsets.UTF_8)

    @Test
    fun signalMatchesWorkedExample() {
        val s = AppJson.decodeFromString<SignalResponse>(read("signal.json"))
        assertEquals("1.0.0", s.modelVersion)
        assertEquals(DataStatus.OK, s.dataStatus)
        assertEquals(61.2, s.global.score, 1e-9)
        assertEquals(SignalLabel.BUY, s.global.signal)
        assertEquals(68, s.global.confidence)
        assertEquals(Regime.GOLD_BULL, s.global.regime)
        assertEquals(7, s.global.components.size)
        assertEquals(s.global.score, s.global.components.sumOf { it.points }, 0.05)
        assertEquals("REAL_YIELD_FALLING", s.global.explanation.positive.first().code)
        assertEquals("NOMINAL_LEVEL_ELEVATED", s.global.explanation.negative.single().code)
        assertEquals(SignalLabel.BUY, s.gramTry.signal)
    }

    @Test
    fun currentPrices() {
        val c = AppJson.decodeFromString<CurrentResponse>(read("current.json"))
        assertEquals(4180.50, c.gold.priceUsd, 1e-9)
        assertEquals(6700.15, c.gramGold.theoreticalTry, 1e-9)
        assertEquals(4265.0, c.gold.high52w, 1e-9)
        assertTrue(c.gold.series.size > 200)
    }

    @Test
    fun everyIndicatorAndItsExtraDecodes() {
        for (code in listOf("REAL_YIELD", "FED", "DXY", "NOMINAL_10Y", "ECON", "ETF", "CENTRAL_BANKS", "GRAM_TRY")) {
            val d = AppJson.decodeFromString<IndicatorDetail>(read("indicator_$code.json"))
            assertEquals(code, d.code)
            when (code) {
                "FED" -> assertEquals(-44.5, AppJson.decodeFromJsonElement<FedExtra>(d.extra).marketImplied.priced12mBp!!, 1e-9)
                "NOMINAL_10Y" -> assertEquals(4.15, AppJson.decodeFromJsonElement<NominalExtra>(d.extra).mean252!!, 1e-9)
                "ECON" -> assertEquals(9, AppJson.decodeFromJsonElement<EconExtra>(d.extra).events.size)
                "CENTRAL_BANKS" -> assertEquals(780.0, AppJson.decodeFromJsonElement<CentralBankExtra>(d.extra).t12Tonnes, 1e-9)
                "GRAM_TRY" -> assertEquals(31.0, AppJson.decodeFromJsonElement<GramExtra>(d.extra).fxLeg.iTryPct!!, 1e-9)
            }
        }
    }

    @Test
    fun historyReportAndHealth() {
        val h = AppJson.decodeFromString<com.goldsignal.model.HistoryResponse>(read("history.json")).rows()
        assertTrue(h.size > 200)
        assertEquals("2026-10-02", h.last().date)
        assertEquals(61.2, h.last().score, 1e-9)
        assertEquals("BUY", h.last().signal)
        val r = AppJson.decodeFromString<com.goldsignal.model.HistoryReport>(read("history_report.json"))
        assertEquals(h.size, r.days)
        assertEquals(100.0, r.signalShare.values.sum(), 0.5)
        val health = AppJson.decodeFromString<com.goldsignal.model.HealthResponse>(read("health.json"))
        assertTrue(health.series.isNotEmpty())
    }

    @Test
    fun eventsAndBacktest() {
        val e = AppJson.decodeFromString<EventsResponse>(read("economic_events.json"))
        assertTrue(e.events.any { it.status == "SCHEDULED" })
        assertTrue(e.events.any { it.code == "NFP" && it.surprise == -70.0 })
        val b = AppJson.decodeFromString<BacktestResponse>(read("backtest_demo.json"))
        assertTrue("demo backtest must be flagged", b.isDemo)
        assertTrue(b.equityCurve.isNotEmpty())
    }
}
